language: rust
rust:
- stable
- beta
- nightly
os:
- linux
after_success: sh scripts/travis-doc-upload.sh
matrix:
  include:
    - os: linux
      rust: nightly
      script: cargo build --features asm

