[package]
name = "tic"
version = "0.1.8"
authors = ["Brian Martin <brayniac@gmail.com>"]

license = "MIT OR Apache-2.0"

description = "[WIP] stats library"

homepage = "https://github.com/brayniac/tic"
documentation = "https://brayniac.github.io/tic"
repository = "https://github.com/brayniac/tic"

readme = "README.md"

keywords = [ "stats", "metrics", "telemetry", "interval" ]

include = [ "src/**/*", "README.md", "LICENSE-*", "Cargo.toml" ]

[dependencies]
bytes = "0.3.0"
clocksource = "0.2.0"
getopts = "0.2.14"
heatmap = "0.6.3"
histogram = "0.6.4"
log = "0.3.6"
mpmc = "0.1.2"
pad = "0.1.4"
rand = "0.3.15"
shuteye = "0.2.0"
tiny_http = "0.5.8"
time = "0.1.36"
waterfall = "0.6.5"

[features]
asm = [ "clocksource/asm" ]
default = []
